server:
  servlet:
    encoding:
      force-response: true
  port: ${SERVER_PORT:8089}
spring:
  profiles:
    include:
      - mongo
      - redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/mutsa-sns }
    username: ${SPRING_DATASOURCE_USERNAME:root }
    password: ${SPRING_DATASOURCE_PASSWORD:1234 }

logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter

jwt:
  secret: ${JWT_SECRET}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}